patternfly/patternfly-design

pattern-library/data-visualization/heat-map/design/overview.md
This PR fixes the rendering of the overview page on the site:
http://www.patternfly.org/pattern-library/data-visualization/heat-map/#/api
=> Added some spaces after the heading hashtags to fix the rendering on the pf.org site

pattern-library/data-visualization/heat-map/design/overview.md
Made a text change for consistency across pages as per #85 
* Removed the Overview heading
=> Remove overview heading from heat maps

pattern-template/design/overview.md
Changes the example link in the pattern-template folder from relative to absolute to conform to our documentation standards
Addresses: #72 
- Changes format of example link in overview.md file
=> Changing link example from relative to absolute

pattern-library/communication/inline-notifications/design/overview.md
This PR Fixes a spacing problem with the Inline Notifications overview title.
Please review @LHinson
=> Fixes a spacing problem with the Inline Notifications overview title

pattern-library/forms-and-controls/toolbar/design/design.md
These updates provide recommendations regarding what text should be provided for icons that display in the toolbar.
https://patternfly.atlassian.net/browse/PTNFLY-2143
* Included table that lists icons that display in the toolbar
* For each icon row, provided tooltip text and aria-label text
_**NOTE:**_ The icons that are included in the table are not visible when viewing the page in github, but should be displayed when the file is pulled into patternfly.org.
=> included table listing icons and icon text

pattern-library/content-views/card-view/design/design.md, pattern-library/content-views/table-view/design/design.md
Pagination was linked to github, rather than the pattern library.
Write a list of changes the PR introduces
* Replaced the github link with http://www.patternfly.org/pattern-library/navigation/pagination/
=> Pagination needs to point to within the pattern library, not github.

pattern-library/communication/toast-notifications/site.md
This PR fixes this bug:
> Toast notifications AngularJS example is showing inline notifications instead
https://github.com/patternfly/patternfly-org/issues/401
=> Corrected the toast-notification angular example

pattern-library/content-views/table-view/design/design.md
List numbering for the table-view design page wasn't correct. 
Fixes ticket #262
* Added two spaces to the lines between the list items, resulting in four spaces which Markdown understands to be indentations.
=> Fixing list numbers on ticket #262.

styles/terminology-and-wording/terminology-and-wording.md
Adding a line to the Capitalization table for Menu items, so that it's clear they should be Headline style.
Fixes ticket #245.
* New line in the table for Menu items, between L and P (as it appeared to be alphabetical)
* Added a space to Tooltips so it lined up with everything else in the table.
=> Fixing the Terminology and Wording part of ticket #245.

pattern-library/navigation/guidelines/design/overview.md
This PR corrects all linter errors for the navigation/guidelines overview page.
=> Fixed the markdown format of the navigation/guidelines overview page

styles/icons/fontawesome.md
Adding the missing List View Vertical Ellipsis icon and Toolbar Sort icon.
In the icon pattern page, missing the List View Vertical Ellipsis icon and Toolbar Sort icon which used in the [list page](http://www.patternfly.org/pattern-library/content-views/list-view/list-view.html). this issue also has been mentioned in here: https://github.com/patternfly/patternfly-org/issues/416
(optional) Include related PRs, Issues and or Jira stories.
https://github.com/patternfly/patternfly-org/issues/416
Before vs After in the patternfly website - Icon http://www.patternfly.org/styles/icons/
p.s: "New" is just for marking which is new, it won't be displayed in the website. :-)
=> Adding the missing fa-icons

pattern-library/data-visualization/pie-chart/design/design.md
A line break in the design.md file under Pie Chart documentation is causing a formatting error. This PR removes that line break to correct Markdown formatting.
@LHinson
=> Remove line break causing formatting error in Markdown

pattern-library/application-framework/launcher/site.md
currently there is a bug that launcher is showing the login implementation. updating to reference the correct rawgit url.
=> updating the app launcher rawgit url

pattern-library/application-framework/masthead/design/design.md, styles/terminology-and-wording/terminology-and-wording.md
* updating documentation to fix “logout” to “log out” on the masthead pattern 
* adding “log out” definition to the t&w page.
=> Terminology and wording updates for "Log out"

pattern-library/application-framework/launcher/site.md
* Fixes the second issue described in the [app launcher patternfly-org issue](https://github.com/patternfly/patternfly-org/issues/451)
* A fix for the first issue is included in [PR 453 in patternfly-org](https://github.com/patternfly/patternfly-org/pull/453)
* The [horizontal](https://github.com/patternfly/patternfly/blob/master/tests/pages/_includes/widgets/navigation/horizontal-primary-nav-bar.html#L15) and [vertical](https://github.com/patternfly/patternfly/blob/master/tests/pages/_includes/widgets/layouts/navbar-vertical.html#L15) navigation includes that are used on the pattern page for the app launcher require a page parameter `applauncher: true` in order for the app launcher to display in the navigation. I included this page parameter in the site.md file for this pattern, so the …
=> Includes page parameter to show app launcher in nav

pattern-library/forms-and-controls/datepicker/site.md
* There isn't an angular example of the Datepicker pattern. This PR includes an update to disable the Angular tab on the [Datepicker pattern page](http://www.patternfly.org/pattern-library/forms-and-controls/datepicker/).
Setting `code_angular` to `false` to disable the tab.
=> disabling Angular tab for Datepicker

pattern-library/communication/empty-state/site.md
The 'url-js-extra' front matter attribute in empty-state site.md file needs to be an array. This PR is targeted to the issue https://github.com/patternfly/patternfly-design/issues/416
=> The 'url-js-extra' front matter attribute needs to be an array

pattern-library/content-views/canvas-view/site.md
* show the code and demo of angular canvas view under the code tab.  
* This PR is targeted to fix the [issue](https://github.com/patternfly/patternfly-design/issues/449).
=> fix-bug: angularjs code tab of canvas view is blank

pattern-library/application-framework/single-sign-on/site.md, pattern-library/cards/trend-card/site.md, pattern-library/communication/about-modal/site.md, pattern-library/communication/empty-state/site.md, pattern-library/communication/experimental-features/site.md, pattern-library/communication/toast-notifications/site.md, pattern-library/communication/wizard/site.md, pattern-library/content-views/table-view/site.md, pattern-library/content-views/tree-list-view/site.md, pattern-library/data-visualization/area-chart/site.md, pattern-library/data-visualization/bar-chart/site.md, pattern-library/data-visualization/donut-chart/site.md, pattern-library/data-visualization/line-chart/site.md, pattern-library/data-visualization/pie-chart/site.md, pattern-library/forms-and-controls/buttons-on-forms/site.md, pattern-library/forms-and-controls/checkbox-filter/site.md, pattern-library/forms-and-controls/errors-and-validation/site.md, pattern-library/forms-and-controls/modal-overlay/site.md, pattern-library/forms-and-controls/slider/site.md, pattern-library/forms-and-controls/sort/site.md, pattern-library/forms-and-controls/textbox-filter/site.md, pattern-library/forms-and-controls/toolbar/site.md, pattern-library/navigation/breadcrumbs/site.md, pattern-library/navigation/pagination/site.md, pattern-library/navigation/vertical-navigation/site.md
This PR is a part of the Jira story below: 
https://patternfly.atlassian.net/browse/PTNFLY-2711
I have added the missing code links to the ```site.md``` for the different repo implementations that are available but not currently linked on pf-org. This would update the pf-org code tab and also update the design status page.
* Changes to the ```site.md``` file
=> Adding missing framework links for patterns to update design status page

pattern-library/cards/base-card/design/design.md, pattern-library/cards/trend-card/design/design.md, pattern-library/cards/utilization-trend-card/design/design.md, pattern-library/communication/empty-state/design/design.md, pattern-library/communication/notification-drawer/design/design.md, pattern-library/forms-and-controls/drag-and-drop/design/design.md, pattern-library/forms-and-controls/dual-pane-selector/DualPaneSelector.md, pattern-library/forms-and-controls/modal-overlay/design/design.md, pattern-library/forms-and-controls/slider/design/design.md, pattern-library/navigation/breadcrumbs/design/design.md, pattern-library/navigation/vertical-navigation/design/design.md
* make sure (optional) is lower case.
* if it's associated with the bold beginning of a list item, make sure it, and the comma that follows, are not bold.
=> Normalize how we present (optional) in list items and headers

script/status.template.hbs
This PR introduces the removal of the WC and CSS table on the design status page, changes jquery to core, and ng 2+ to 4+ as related to this jira story: https://patternfly.atlassian.net/browse/PTNFLY-2712
* Removal of WC and CSS
* jQuery to Core
* Ng 2+ to 4+
=> Remove WC and CSS tables, jQuery to Core, and 2+ to 4+

pattern-library/application-framework/single-sign-on/site.md, pattern-library/communication/experimental-features/site.md, pattern-library/forms-and-controls/modal-overlay/site.md, pattern-library/forms-and-controls/textbox-filter/site.md
Related to this jira story:  https://patternfly.atlassian.net/browse/PTNFLY-2783
and this recently merged PR: https://github.com/patternfly/patternfly-org/pull/528
Updated site.md to enable code tab to display experimental features, modal overlay, textbox-filter and single-sign-on on pf-org
Experimental Features: [here](https://rawgit.com/amarie401/patternfly-org/missing-code-examples-dist/_site/pattern-library/communication/experimental-features/#code)
Single Sign On: [here](https://rawgit.com/amarie401/patternfly-org/missing-code-examples-dist/_site/pattern-library/application-framework/single-sign-on/#code)
Textbox Filter: [here](https://rawgit.com/amarie401/patternfly-org/missing-code-examples-dist/_site/pattern-library/forms-and-controls/textbox-filter/#code)
Modal Overlay: …
=> Updating site.md for missing code examples

pattern-library/content-views/table-view/site.md, pattern-library/forms-and-controls/buttons-on-forms/site.md, pattern-library/forms-and-controls/data-input/site.md, pattern-library/forms-and-controls/errors-and-validation/site.md, pattern-library/forms-and-controls/field-labeling/site.md, pattern-library/forms-and-controls/filter/site.md, pattern-library/forms-and-controls/help-on-forms/site.md, pattern-library/navigation/vertical-navigation/site.md
This PR is a part of the Jira story below: 
https://patternfly.atlassian.net/browse/PTNFLY-2787 and fixes #571 
I have added the missing code links to the ```site.md``` for the react implementations that are available but not currently linked on pf-org. This would update the pf-org code tab and also update the design status page.
* Changes to the ```site.md``` file
Note: The syntax hints pattern does not have a `site.md` file in the design repo and is also not on pf-org either, so I was not able link it for the example you wanted to use @jgiardino. Is there a reason for this? @mcarrano ?
=> Adding missing react links to update design status and org

pattern-library/forms-and-controls/field-labeling/site.md, pattern-library/forms-and-controls/help-on-forms/site.md
Fixing error from last PR here: https://github.com/patternfly/patternfly-design/pull/616
* Adding field level help to help on forms example instead of field-labeling
=>  Adding field level help to help on forms example

pattern-library/forms-and-controls/toolbar/design/design.md
Fixed #642
* Currently, the sort icon displayed and guidance are inconsistent on " Form and control"- Toolbar, design page.Sort image and related guidance need to be changed.
-see more detail here:http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/#design
* Sort image
* Class name
* related guidance
=> Modified Sort icon and guidance on Toolbar design page

pattern-library/communication/notification-drawer/site.md, pattern-library/data-visualization/utilization-bar-chart/site.md, pattern-library/forms-and-controls/inline-edit/site.md, pattern-library/forms-and-controls/modal-overlay/site.md, pattern-library/forms-and-controls/slider/site.md, pattern-library/navigation/pagination/site.md
* This PR is to update the design status page and pf-org with framework links that have been recently merged 
* Related to this story/issue: https://github.com/patternfly/patternfly-org/issues/547
* site.md is updated to show framework links
=> Updating framework links for status page and pf-org

CONTRIBUTING.md
This PR introduces updates to the contributing.md with documentation on how to become a maintainer with slight modification for pf-design. This is related to this [PR](https://github.com/patternfly/patternfly-react/pull/302) from @LHinson
* contributing.md
=> how to become a maintainer doc updates

pattern-library/navigation/breadcrumbs/design/design.md
Updating breadcrumbs documentation regarding icon usage
Closes #700 
* Changed "fa-angle-double-right" to "fa-angle-right"
=> Fixing inconsistency in breadcrumbs documentation

.gitignore, pattern-library/cards/base-card/site.md, pattern-library/cards/trend-card/site.md, pattern-library/communication/about-modal/site.md, pattern-library/communication/empty-state/site.md, pattern-library/communication/inline-notifications/site.md, pattern-library/communication/toast-notifications/site.md, pattern-library/communication/wizard/site.md, pattern-library/content-views/list-view/site.md, pattern-library/content-views/table-view/site.md, pattern-library/content-views/tree-list-view/site.md, pattern-library/data-visualization/donut-chart/site.md, pattern-library/data-visualization/sparkline/site.md, pattern-library/forms-and-controls/sort/site.md, pattern-library/forms-and-controls/textbox-filter/site.md, pattern-library/forms-and-controls/toolbar/site.md, pattern-library/navigation/pagination/site.md, pattern-library/navigation/vertical-navigation/site.md
Link patternfly-ng to gh-pages instead of rawgit.
Fixes https://github.com/patternfly/patternfly-org/issues/634
=> patternfly-ng: fix broken links
