pattern-library/content-views/table-view/design/design.md
pattern-library/data-visualization/heat-map/design/overview.md

In reference to issue #78 - Updated table pattern design documentation to reference the new tool bar pattern.
* Updated terminology from "Data Toolbar" to "Toolbar"
* Linked to Toolbar pattern

Updated toolbar reference on Table pattern design documentation

---

pattern-library/communication/about-modal/design/design.md

Learning Git exercise, addressed open issue #84 
Removed header "Description"
Write a list of changes the PR introduces
n/a

Removing “Description” header

---

.gitignore
pattern-library/communication/notification-drawer/site.md

Prepares notification drawer pattern for posting to patternfly.org
- Adds site.md file to notification drawer pattern
- updates .gitignore file

Adding site.md to notification drawer pattern and updated .gitignore

---

pattern-library/data-visualization/bar-chart/design/overview.md

Fixed link to Line Chart pattern

Fixed bug #80

---

pattern-library/communication/notification-drawer/site.md

Correctly display the design.md file in the design tab
Please review @LHinson

Correctly display the design.md file in the design tab

---

pattern-library/communication/notification-drawer/design/overview.md

fixing the anchor links on the notification drawer

fixing the anchor links on the notification drawer

---

pattern-library/communication/about-modal/design/design.md
pattern-library/communication/about-modal/design/overview.md

fixing anchor links and spacing

fixing anchor links and spacing

---

pattern-library/cards/base-card/site.md

adding site.md to base card

---

pattern-template/site.md

In this PR I've introduced a site.md file to the pattern-template folder.

Added a site.md to the pattern-template

---

pattern-library/cards/base-card/site.md

This PR introduces the code samples to the base-card site.md file.

Referenced the base-card example from the base-card site.md

---

pattern-template/design/design.md
pattern-template/design/overview.md

updating the template. mind taking a look @andresgalante @bleathem

making updates to the template

---

pattern-library/application-framework/masthead/design/design.md

Fixed the indentation of the nested bullets of the masted design.md file

Fixed the indentation of the nested bullets of the masted design.md file

---

pattern-library/forms-and-controls/drag-and-drop/design/design.md
pattern-library/forms-and-controls/drag-and-drop/design/overview.md

fixing the formatting for drag and drop

fixing the formatting for drag and drop

---

pattern-library/content-views/table-view/site.md

Enable the basic features of Datatables on patternfly.org, like pagination, select row, filter rows and so on.
It aims to fix the [bug](https://github.com/patternfly/patternfly/issues/577).

Table View - Selected Row color not being applied

---

pattern-library/data-visualization/bar-chart/design/design.md

reformatted bullets for easy fix issue

reformatted bullets

---

pattern-library/data-visualization/bullet-chart/design/overview.md

capitalized 'bullet graph' text string for the github workshop.

capitalized ‘bullet graph’ text string

---

pattern-library/data-visualization/heat-map/design/overview.md

Updated capitalization and wording around Heat Maps
Issue #214 
* Updated capitalization

Updated capitalization

---

pattern-library/communication/wizard/design/overview.md

Deleted Heading

---

styles/icons/icomoon.md

Not sure how to track down the icon string...
Write a few sentences describing the overall goals of the pull request's commits.
(optional) Include related PRs, Issues and or Jira stories.
Write a list of changes the PR introduces
* Change 01
* Change 02
* Change 03

Added resources-full, sans pf icon string

---

pattern-library/forms-and-controls/toolbar/design/design.md
styles/icons/fontawesome.md
styles/icons/icomoon.md

This won't affect the display on github, but will add the CSS classes when rendered on the site.

Adds CSS classes to the forms-and-controls/toolbar/design table

---

pattern-library/application-framework/login-page/design/design.md

Updated formatting for issue #233

Issue #233

---

pattern-library/content-views/canvas-view/design/design.md

Updates formatting of the canvas-view pattern to address bullet rendering issues
closes #253 
- canvas-view/design.md
- indented list
- changed bullet symbols for easier typing
- updated numbering for easier future editing

Editing bullet points to fix rendering issues

---

pattern-library/navigation/vertical-navigation/design/design.md
pattern-library/navigation/vertical-navigation/design/overview.md

Adds masthead links to vertical navigation pattern
closes #50 
design.md
- Add masthead blurb to mirror horizontal nav patter
overview.md
- Add link to masthead reference

Adding links to masthead pattern in vertical nav

---

pattern-library/content-views/table-view/design/overview.md

Removes unnecessary header elements on table-view/overview.md
closes #209

Removing unnecessary headers on table view

---

pattern-library/data-visualization/bar-chart/design/design.md

Updated indentation and spacing to improve  bullet rendering
Closes #210

Improving bullet rendering

---

pattern-library/forms-and-controls/sort/design/design.md

Made some minor updates to the source code of Sort.

New Updates for Sort

---

package.json
pattern-library/application-framework/login-page/site.md
pattern-library/cards/aggregate-status-card/site.md
script/pattern-walk.js
script/status.template.hbs
script/verify-site-includes.js

This PR introduces a clickable link to a pattern's implementation for the various frameworks.  It is staged here:
http://bleathem.github.io/patternfly-design/status/

Exposed the site.md impl_<framework> details on the status page

---

pattern-library/application-framework/launcher/site.md

updating design status page: launcher component

updating design status page: launcher component

---

pattern-library/cards/aggregate-status-card/site.md
pattern-library/cards/base-card/site.md
pattern-library/cards/trend-card/site.md
pattern-library/cards/utilization-bar-card/site.md
pattern-library/cards/utilization-trend-card/site.md
pattern-library/communication/about-modal/site.md
pattern-library/communication/empty-state/site.md
pattern-library/communication/notification-drawer/site.md
pattern-library/communication/toast-notifications/site.md
pattern-library/communication/wizard/site.md
pattern-library/content-views/card-view/site.md
pattern-library/content-views/list-view/site.md
pattern-library/content-views/table-view/site.md
pattern-library/dashboard/dashboard-layout/site.md
pattern-library/data-visualization/area-chart/site.md
pattern-library/data-visualization/bar-chart/site.md
pattern-library/data-visualization/donut-chart/site.md
pattern-library/data-visualization/line-chart/site.md
pattern-library/data-visualization/pie-chart/site.md
pattern-library/data-visualization/sparkline/site.md
pattern-library/data-visualization/utilization-bar-chart/site.md
pattern-library/forms-and-controls/toolbar/site.md
pattern-library/navigation/breadcrumbs/site.md
pattern-library/navigation/horizontal-navigation/site.md
pattern-library/navigation/vertical-navigation/site.md

updating impl_* for various site.md files for core

---

pattern-library/cards/aggregate-status-card/site.md
pattern-library/cards/base-card/site.md
pattern-library/cards/trend-card/site.md
pattern-library/cards/utilization-bar-card/site.md
pattern-library/cards/utilization-trend-card/site.md
pattern-library/communication/about-modal/site.md
pattern-library/communication/empty-state/site.md
pattern-library/communication/notification-drawer/site.md
pattern-library/communication/toast-notifications/site.md
pattern-library/communication/wizard/site.md
pattern-library/content-views/card-view/site.md
pattern-library/content-views/list-view/site.md
pattern-library/content-views/table-view/site.md
pattern-library/dashboard/dashboard-layout/site.md
pattern-library/data-visualization/area-chart/site.md
pattern-library/data-visualization/bar-chart/site.md
pattern-library/data-visualization/donut-chart/site.md
pattern-library/data-visualization/line-chart/site.md
pattern-library/data-visualization/pie-chart/site.md
pattern-library/data-visualization/sparkline/site.md
pattern-library/data-visualization/utilization-bar-chart/site.md
pattern-library/forms-and-controls/toolbar/site.md
pattern-library/navigation/breadcrumbs/site.md
pattern-library/navigation/horizontal-navigation/site.md
pattern-library/navigation/vertical-navigation/site.md

Re-factored impl_html to impl_jquery in the site.md files

Re-factored impl_html to impl_jquery in the site.md files

---

pattern-library/data-visualization/pie-chart/design/design.md
pattern-library/data-visualization/pie-chart/design/overview.md

Made minor changes to sentence structure to clarify the design notes.

Minor sentence structure changes.

---

pattern-library/forms-and-controls/data-input/design/overview.md

Edit structure to improve clarity, bring document into a consistent tone and style. Add hyperlinks where necessary.
* Restructures paragraph format to include an Overview and Details section under each data input type section.
* Adds links to internal sections of the document as well as links to documentation elsewhere on the PatternFly website.
@LHinson @essjaysee

Data Input Documentation

---

pattern-library/application-framework/launcher/site.md

I think impl needs to be changed to "code" for the angular line.

trying to fix code tab

---

pattern-library/application-framework/launcher/site.md

Reverts patternfly/patternfly-design#371

Revert "removing angular for now to try and trouble shoot what’s going on wit…"

---

pattern-library/application-framework/launcher/site.md

trouble shooting code issue....

removing angular code for now

---

pattern-library/communication/experimental-features/site.md

…since there is no code to date.

removing code references in experimental features 

---

pattern-library/application-framework/launcher/site.md

updating correct code and impl references

updating site.md for launcher

---

pattern-library/content-views/tree-list-view/site.md

no code yet for the tree list view so marking as false

---

pattern-library/cards/aggregate-status-card/site.md
pattern-library/cards/base-card/site.md
pattern-library/cards/trend-card/site.md
pattern-library/cards/utilization-bar-card/site.md
pattern-library/cards/utilization-trend-card/site.md
pattern-library/communication/about-modal/site.md
pattern-library/communication/inline-notifications/site.md
pattern-library/communication/notification-drawer/site.md
pattern-library/communication/toast-notifications/site.md
pattern-library/communication/wizard/site.md
pattern-library/content-views/canvas-view/site.md
pattern-library/content-views/card-view/site.md
pattern-library/content-views/list-view/site.md
pattern-library/data-visualization/area-chart/site.md
pattern-library/data-visualization/donut-chart/site.md
pattern-library/data-visualization/heat-map/site.md
pattern-library/data-visualization/line-chart/site.md
pattern-library/data-visualization/sparkline/site.md
pattern-library/data-visualization/utilization-bar-chart/site.md
pattern-library/forms-and-controls/datepicker/site.md

… to address angular code bugs on the site due to a path change.

updating “directive” to “component” in the angular path

---

pattern-library/cards/utilization-trend-card/site.md
pattern-library/data-visualization/heat-map/site.md
pattern-library/data-visualization/utilization-bar-chart/site.md

Should fix the following angular code examples:
* utilization trend card
* heat map
* utilization bar  chart

Fixes additional angular code examples

---

styles/terminology-and-wording/terminology-and-wording.md

fixes typos

---

pattern-library/data-visualization/pie-chart/design/design.md
pattern-library/data-visualization/pie-chart/design/overview.md

This PR updates the documentation for the pie chart pattern to meet goals outlined in the documentation checklist. It adds use case scenarios and clarifies language.
JIRA Ticket: PTNFLY-2398
* Adds use case scenarios to clarify when it is and is not appropriate to use a Pie Chart
* Clarifies language (making sure that elements of the pattern are addressed with a consistent vocabulary)
@Essjaysee @LHinson

Update Pie Chart Documentation

---

pattern-library/communication/comments/site.md

* Adding the site.md file for Comments

Adding the site.md file for the comments UI

---

pattern-library/forms-and-controls/help-on-forms/site.md

- Created and uploading site.md file that was missing #353

- Created site.md file

---

styles/terminology-and-wording/terminology-and-wording.md

updating terminology and wording to include guidance on capitalization

---

pattern-library/forms-and-controls/errors-and-validation/design/overview.md

fixing the link for inline notifications on this page.

fixing link

---

pattern-library/application-framework/login-page/design/overview.md

This updates the social login page to show the brand guidelines for each logo used.

updates social login design doc

---

pattern-library/application-framework/single-sign-on/design/overview.md

* Adding the references to third party branding guidelines to cover use of third party logos in these screens.
* Updated overview.md to add disclaimer text and links.
- [ x] The overview.md, design.md and site.md files, for this design have been commited and pushed to the patternfly-design repository, for review.

Add logo usage disclaimer.

---

pattern-library/communication/comments/design/design.md
pattern-library/communication/notification-drawer/design/design.md
pattern-library/forms-and-controls/find/design/design.md
pattern-library/forms-and-controls/progressive-disclosure/design/overview.md
pattern-library/navigation/horizontal-navigation/design/design.md
pattern-library/navigation/horizontal-navigation/design/overview.md

* normalize the spelling of "kebab" and "dropdown"

fix misspellings of kebab and dropdown

---

pattern-library/communication/empty-state/design/overview.md
pattern-library/communication/experimental-features/design/design.md
pattern-library/communication/experimental-features/design/overview.md

* Updates to /pattern-library/communication/empty-state/ and /pattern-library/communication/experimental-features per https://docs.google.com/document/d/185YDTyxmHaqiw2PfDT6QyDpYpErFY2AfWNMw0F5cY-c/edit?ts=5a4fc8aa#

punctuation and wording updates

---

pattern-library/communication/about-modal/design/design.md
pattern-library/communication/about-modal/design/overview.md
pattern-library/forms-and-controls/help-on-forms/design/design.md
pattern-library/forms-and-controls/help-on-forms/design/overview.md
pattern-library/forms-and-controls/syntax-hints/design/design.md
pattern-library/forms-and-controls/syntax-hints/design/overview.md

Move "what's not covered in the current design" to the design panel per our feedback discussion.

move "what's not covered in the current design" to the design panel

---

pattern-library/communication/wizard/design/design.md
pattern-library/communication/wizard/design/overview.md

* There are currently implementation issues with the design of the embedded wizard so a decision was made to remove this from the pattern at this time until and unless there is a further product need for this.
* Closes #532 
References to embedded wizard in overview.md and design.md files have been commented out.
- [ x] A GitHub issue was created and reviewed with the PatternFly community.
- [x ] The overview.md, design.md and site.md files, for this design have been commited and pushed to the patternfly-design repository, for review.

Commented out embedded wizard references

---

pattern-library/communication/loading-state/site.md

* updated the missing dashes which fixes #580

added 3 missing dashes underneath the front matter of the site.md file

---

pattern-library/content-views/tree-list-view/design/design.md
pattern-library/content-views/tree-list-view/design/overview.md

* Updates to copy per our feedback discussion.

copy updates to tree-list-view overview and design

---

pattern-library/application-framework/login-page/site.md

Updating the design status page to point to the new login code on the pf test pages.
Related to this PR in pf-org: https://github.com/patternfly/patternfly-org/pull/526
* Design status login pattern points to new link

Updating login page link to point to new login code on test pages

---

pattern-library/application-framework/login-page/design/overview.md

Fixes #586 
`site.md` is updated with correct name and points to correct link.

Fixed broken link to multi factor login

---

pattern-library/data-visualization/utilization-bar-chart/design/design.md
pattern-library/data-visualization/utilization-bar-chart/design/overview.md

Updates to copy per our feedback discussion.

Updates to utilization-bar-chart

---

pattern-library/forms-and-controls/slider/site.md

Related to this jira story:  https://patternfly.atlassian.net/browse/PTNFLY-2783
and these recently merged PR's:
https://github.com/patternfly/patternfly-design/pull/596 & https://github.com/patternfly/patternfly-org/pull/528
Slider: [here](https://rawgit.com/amarie401/patternfly-org/missing-code-examples-dist/_site/pattern-library/forms-and-controls/slider/#code)

Updating site.md for slider code example for pf-org to consume

---

pattern-library/content-views/card-view/design/design.md
pattern-library/content-views/list-view/design/design.md
pattern-library/content-views/table-view/design/design.md

* added links to Table, List, and Card view about Loading State
*closes #467 #468 #469

Adding links to Table, List and Card view about Loading State.

---

pattern-library/forms-and-controls/errors-and-validation/design/overview.md

Closes #572
* For better understanding of when validation disappears after a user fixes the field entry, adding “and the widget loses focus" on the description.
* Adds wording “and the widget loses focus" on description.

Update guideline of "Validation and Errors" for Forms and Controls

---

pattern-library/content-views/tree-list-view/site.md

Expose tree list view demo on patternfly.org site. @dgutride Please review this PR 😊

chore(tree-list-view): add tree-list-view to patternfly.org

---

pattern-library/application-framework/login-page/site.md

PR to add `doc.md` file for dev notes for login page. 
Related to this recently merged PR: https://github.com/patternfly/patternfly-org/pull/542
* Changes to site.md to add doc.md file for login page

Adding doc.md file for login page to consume dev notes on pf-org

---

pattern-library/forms-and-controls/sort/design/design.md

* Fix tow UI issues after #636 has been merged : 
1) Table is missing 
2) Images of sort icon  are repeated. 
* See more detail on Patternfly http://www.patternfly.org/pattern-library/forms-and-controls/sort/#design
* Added {:.table .table-striped .table-bordered} to the end 
* Delete code for insert image in the Table.

Fix UI issues related to #636 has been merged 

---

pattern-library/navigation/context-selector/site.md

* This PR is to update the site.md with the code.md for the context selector example for pf-org consumption.   
* Related to this recently merged PR: https://github.com/patternfly/patternfly-org/pull/532
* Updating site.md with code.md for context-selector component

updating site.md with code.md for context-selector - pf-org

---

pattern-library/forms-and-controls/inline-edit/site.md

This PR is to update the `site.md` for the inline-edit example to display on pf-org
Related to this recently merged PR: https://github.com/patternfly/patternfly-org/pull/558
* `site.md`

update site.md for inline-edit to display on pf-org

---

pattern-library/content-views/list-view/design/design.md

This PR will update the List View design page to detail the color values for each state including hover, selected, open, edit and disabled states. This will help clarify these states to ensure consistency across repos.
* Updated design.md

Update list view design doc to include row styling details

---

pattern-library/application-framework/masthead/site.md
pattern-library/data-visualization/bullet-chart/site.md
pattern-library/navigation/vertical-navigation/site.md

* Update framework links for recent merges for pf-org
Related to this issue: https://github.com/patternfly/patternfly-org/issues/573
* `site.md` updated

update site links for frameworks

---

pattern-library/forms-and-controls/actions/site.md

In browsing the library today, I noticed that the Actions pattern contributed 2 months ago is not showing in the navigation. Upon investigation I found that there was no site.md file. This PR adds it.
* Add a site.md file for the Actions pattern.

Add site.md to Actions pattern

---

styles/icons/icons.json

This PR is targeted to fix the [issue](https://github.com/patternfly/patternfly/issues/1065).
@mcarrano @amarie401 @dgutride Could you review this PR whenever you got the chance ?
Reverse the "contextual usage".

fix(icons): Update contextual usage

---

pattern-library/content-views/list-view/design/design.md

* Update RGB values for background colors on Design page to the correct values.
* See PatternFly Core issue: https://github.com/patternfly/patternfly/issues/1082
* Update design.md

Update List View color values for row states to match correct colors

---

pattern-library/application-framework/launcher/site.md
pattern-library/forms-and-controls/filter/site.md

Update the website `site.md` links for framework implementations
* Application Launcher - React
* Filter - NG

update site links

---

pattern-library/navigation/pagination/site.md

* Update the `site.md` for the pagination example for pf-org
Related to this PR: https://github.com/patternfly/patternfly-org/pull/643
* `site.md` is updated

Update site.md for pagination example

---

styles/icons/icons.json

* Updating icon page with new types and descriptions to include more use cases.
* Added type and description for fa-ban
* ~~Updated type and description for fa-refresh to include two different use cases~~ Will be addressed in separate PR
* Added new pending icon as a variation of pficon-pending

Updating icons

---

pattern-library/communication/classification-banner/design/design.md

Classified should be red, unclassified should be green.

Update classified/unclassified color associations of classification-banner design

---

pattern-library/communication/classification-banner/design/overview.md

Unclassified should be green, classified should be red.

Update classified/unclassified color associations
